version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5001:5001"
    logging:
      driver: json-file
    volumes:
      - ./logs/backend:/var/log/backend

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5000:5000"
    logging:
      driver: json-file
    volumes:
      - ./logs/frontend:/var/log/frontend

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      # Здесь монтируем внешнее хранилище для индекса и чанков:
      - ./loki-storage/index:/loki/index
      - ./loki-storage/chunks:/loki/chunks
      - ./loki-storage/cache:/loki/boltdb-cache

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    privileged: true
    depends_on:
      - loki

  grafana:
    image: grafana/grafana-oss:10.2.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=903903
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
